_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.19.8
            "8":
                - 3
                - 5
                - 9
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 300
gp_weight:
    value: 10
latent_dim:
    value: 128
learning_rate:
    value: 0.0001
n_critic:
    value: 3
set_name:
    value: n_critic_3_WB
